In [1]:
import numpy as np

In [7]:
iToW = np.array([[0, -1, 10000],
                 [1, 0, 15000], 
                 [0, 0, 1]])
iToW

array([[    0,    -1, 10000],
       [    1,     0, 15000],
       [    0,     0,     1]])

In [8]:
X = np.array([[2000, 5000, 1]]).transpose()
X

array([[2000],
       [5000],
       [   1]])

In [9]:
np.matmul(iToW, X)

array([[ 5000],
       [17000],
       [    1]])

In [11]:
1 / X

array([[5.e-04],
       [2.e-04],
       [1.e+00]])